### PR TITLE
Nestorcayananjr/tutorialtool

### PR DESCRIPTION
**Pull request by nestorcayananjr**
# Issue Type

- [x] Bug
- [x] Feature
- [ ] Tech Debt

# Issue Description & Business Use Case

Added a tutorial modal that shows first time users how to use the application. Additionally got rid of a bug that showed a '0' on the home page.

# Ticket Item

[Trello Ticket](https://trello.com/c/bSgX37BL)

# Steps to Reproduce Bug / Validate Feature / Confirm Tech Debt Fix

1. Pull down latest changes and install latest dependencies.
2. Run the dev branch and navigate to localhost:3000
3. See that the modal tutorial renders, clicking continue should render the next tutorial while clicking cancel should stop tutorial modals from rendering.
4. Clicking outside of tutorial modal should also not do anything.
5. Check the browser devtools and navigate to the application tab and check for the vista cookie.
6. Refresh the page and modals should not render.

# Previous behavior

Modals were not previously being used. 0 was appearing on the homepage

# Expected behavior

Modals should render upon time visiting the application.

### CODE REVIEW

**Review by heyitsmattox — APPROVED** [review]
Good modal and use case.

**Review by lucascontreras — COMMENTED** [review]
Hey @nestorcayananjr! Love this feature, works as described on my end.
Just one question, why do you have 3 components for the modals instead of a single reusable component with the title and description being props?

**Comment by nestorcayananjr** [comment]
@lucascontreras I think that's a very legitimate question - I did not think about taking that approach. I think there can be a reusable component made for the last two, since they are in the same position to the page. Meanwhile, the first modal is in a different position and I'm not sure how I would change styling via props. I'll update my commit to take the approach you suggested for the last two modals and will leave the first one as is.

**Review by lucascontreras — APPROVED** [review]
Hey Nestor, this looks clean. Approving.

**Pull request merged**
